# Generated by Django 3.0 on 2020-04-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200422_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='io_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='detail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='io_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3),
        ),
    ]
