# Generated by Django 3.0 on 2020-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20200429_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('cash', 'cash'), ('investment', 'investment'), ('pension', 'pension')], default='cash', max_length=60, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='account',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Initial Value'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='io_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3, verbose_name='In-Out'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='io_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3, verbose_name='In-Out'),
        ),
    ]
