# Generated by Django 3.0 on 2020-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20200502_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_seassonal',
            field=models.BooleanField(default=False, verbose_name='Seassonal'),
        ),
    ]
