# Generated by Django 3.0 on 2020-05-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0010_subcategory_is_seassonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('equal', 'equal'), ('proportional', 'proportional')], default='equal', max_length=60, verbose_name='Rule')),
                ('coefficient_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('constant_value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, max_length=100, null=True)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Subcategory')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='budget.Subcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
