# Generated by Django 3.0 on 2020-05-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Account'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='coefficient_value',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='constant_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('equal to', 'equal to'), ('proportional to', 'proportional to')], default='equal', max_length=60, verbose_name='Rule'),
        ),
    ]
