# Generated by Django 3.0 on 2020-05-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20200504_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='coefficient_value',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='constant_value',
        ),
        migrations.AddField(
            model_name='rule',
            name='coefficient',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Coefficient Value'),
        ),
        migrations.AddField(
            model_name='rule',
            name='constant',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='Constant Value'),
        ),
    ]
