# Generated by Django 3.0 on 2020-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20200504_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='io_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3, verbose_name='In-Out'),
        ),
        migrations.AddField(
            model_name='rule',
            name='target_io_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=3, verbose_name='In-Out'),
        ),
    ]
